Improve Vtiger-odoo13
JayVora-SerpentCS/odoo-vtiger pull request #11
Opened 2020-12-02 08:03 UTC by dhiren-scs

Fix the multiple line issue of saleorder,Purchase order and Invoice.

2020-12-02 09:07 UTC, JayVora-SerpentCS commented
@hiren-serpentcs pls review

2020-12-11 11:45 UTC, hiren-serpentcs commented on vtiger_connector_calendar/models/res_company.py
>                          calendar_vals.update({'start': str(start_date)})
> str(start_date)

Do we need the typecast here?

2020-12-11 11:56 UTC, hiren-serpentcs requested changes

2020-12-11 11:56 UTC, hiren-serpentcs commented on vtiger_connector_calendar/models/res_company.py
>                          split_time = str(get_start_time).split(':')
No need to typecast and split, we can directly get hours by get_start_time.hour

2020-12-11 11:56 UTC, hiren-serpentcs commented on vtiger_connector_calendar/models/res_company.py
>                          calendar_vals.update({'start': str(start_date)})
remove typecasting for date/datetime fields

2020-12-11 11:56 UTC, hiren-serpentcs commented on vtiger_connector_invoice/models/res_company.py
> +                    line_req = requests.get(line_url, auth=(
Add docstring for why we added the second API call to vtiger

2020-12-11 11:56 UTC, hiren-serpentcs commented on vtiger_connector_sales/models/res_company.py
> +from requests.auth import HTTPBasicAuth
are we using HTTPBasicAuth anywhere on the code?

2020-12-11 12:19 UTC, hiren-serpentcs requested changes

2020-12-11 12:19 UTC, hiren-serpentcs commented on vtiger_connector_sales/models/res_company.py
>                  self.update_existing_sale_Quotes(result)
Check update_existing_sale_Quotes and update_existing_sale_order methods, both are having the exact same code

2020-12-17 06:51 UTC, JayVora-SerpentCS commented
use labels wisely @hiren-serpentcs

2020-12-17 11:09 UTC, hiren-serpentcs requested changes

2020-12-17 11:09 UTC, hiren-serpentcs commented on vtiger_connector_partner/models/res_company.py
>                          'website': res.get('website'),
We can create a new method and that will work on the query data to avoid the code duplication

2021-01-06 13:21 UTC, JayVora-SerpentCS commented
How far we have reached ?

2024-07-24 05:51 UTC, JayVora-SerpentCS commented
@chandni-serpentcs pls see

2024-11-12 05:54 UTC, closed without merging