Improve Vtiger-odoo12
JayVora-SerpentCS/odoo-vtiger pull request #13
Opened 2020-12-02 08:21 UTC by dhiren-scs

Fix the multiple line issue of saleorder and Purchase order.

2020-12-11 12:00 UTC, hiren-serpentcs requested changes

2020-12-11 12:00 UTC, hiren-serpentcs commented on vtiger_connector_purchase/models/res_company.py
> +from requests.auth import HTTPBasicAuth
Remove HTTPBasicAuth if we are not using it anywhere

2020-12-11 12:00 UTC, hiren-serpentcs commented on vtiger_connector_purchase/models/res_company.py
> +                    line_url += "/restapi/v1/vtiger/default/retrieve?id=" + po_id
Add docstring for the second api call

2020-12-11 12:16 UTC, hiren-serpentcs requested changes

2020-12-11 12:16 UTC, hiren-serpentcs commented on vtiger_connector_sales/models/res_company.py
>                  self.update_existing_sale_Quotes(result)
check update_existing_sale_order and update_existing_sale_Quotes methods, they both are having exact same code

2020-12-17 05:54 UTC, JayVora-SerpentCS commented
@hiren-serpentcs do tell me when its ready to go

2020-12-17 06:42 UTC, hiren-serpentcs approved these changes

2020-12-17 06:46 UTC, hiren-serpentcs commented
@JayVora-SerpentCS 
LGTM :thumbsup:

Do we need to assign this to QA?

2020-12-17 06:49 UTC, JayVora-SerpentCS commented
Talk to Savitri. She would assign to new comer Keval.
I am merging meanwhile.
Thanks.

2020-12-17 06:49 UTC, merged